---
abstract: 'Quickly create tickets in specific queues with default values'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-QuickCalls
no_index:
  directory:
    - html
    - inc
    - xt
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-quickcalls
version: '1.04'
x_module_install_rtx_version: '0.43'
x_requires_rt: 4.4.0
x_rt_too_new: 5.2.0
